### ISSUE TITLE
Make usage example more clear

### ISSUE THREAD

**Issue by djsandb** [davedoesdev/frame-stream#12]
It (the first example in the readme) shows how to pipe the socket data into the decoder, but not how to retrieve the resulting framed messages. I've tried the socket 'data' message, but it seems to still have raw, unframed data.

**Comment by davedoesdev** [comment]
@djsandb you're right, the README needs updating. I'll see what I can do but it might be a few days until I get round to it.

**Comment by djsandb** [comment]
I'm actually needing clarification on retrieving the framed messages. 

`const net = require('net');`
`var frame = require('frame-stream')`
`var decode = frame.decode()`
`var tcpServer = net.createServer(function(socket) {`
  `  socket.pipe(decode)`
`});`
`decode.on('data', (msg) => {`
`    console.log(msg.toString());`
`});`
`tcpServer.listen(1234);`

I assumed it would be something along those lines, but that isn't working.

**Comment by davedoesdev** [comment]
@djsandb I've updated the example in the README.
It works for me and I've added it to the test suite, which passes.

**Comment by djsandb** [comment]
I was not sending the correct length prefix. The code works now. It's good that the README is more clear now. Thanks.

**Comment by davedoesdev** [comment]
Thanks for raising the issue, appreciate it.
