### ISSUE TITLE
Make an optional timeout options property on how long to wait until resetting/timing out/trying again

### ISSUE THREAD

**Issue by brandonros** [davedoesdev/frame-stream#18]

**Comment by brandonros** [comment]
Some kind of watchdog that can detect if it's been at least 1000ms without the buffer's length having grown while expecting `foo` length message, just reset back to initial state as if we're waiting for the length-prefix of another message from a clean state

Otherwise, if a message fails to be received, when a client retries, it'll just get added to the already stuck message and then it all falls apart from there.

**Comment by davedoesdev** [comment]
Are you using an unreliable transport stream?

**Comment by davedoesdev** [comment]
@brandonros I don't quite understand the use case here.
Frame stream assumes the underlying stream is reliable, so doesn't try to cope with timeouts etc.

**Comment by davedoesdev** [comment]
Sorry, don't want to cope with unreliable carrier stream.
