### ISSUE TITLE
encode frame length as unsigned int

### ISSUE THREAD

**Issue by derhuerst** [davedoesdev/frame-stream#7]
As the frame length is by definition positive, why not use `readUInt*`?

Happy to submit a PR! Note that this would be a breaking change.

**Comment by derhuerst** [comment]
FYI: I've found [`length-prefixed-stream`](https://github.com/mafintosh/length-prefixed-stream). Since it uses `varint`, I will use that one.

**Comment by davedoesdev** [comment]
Fixed by #9
